import duality_reflexivity_normed_linear_banach_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace duality_reflexivity_normed_linear_banach_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end duality_reflexivity_normed_linear_banach_theorem_canonical_lane_mathlib
end HautevilleHouse
